config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'properties#index'
  resources :properties

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)

    if @property.save
      redirect_to @property
    else
      render 'new'
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])

    if @property.update(property_params)
      redirect_to @property
    else
      render 'edit'
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    redirect_to properties_path
  end

  private
  def property_params
    params.require(:property).permit(
      :name,
      :description,
      :address,
      :province,
      :city,
      :country,
      :valuation,
      :dimension)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyManager</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
    .mdl-layout {
      align-items: center;
      justify-content: center;
    }
    </style>

  </head>

  <body data-no-turbolink>
    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-color--gray-100">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">Property Manager</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <%= link_to "View all Properties", properties_path, class: "mdl-navigation__link"%>
            <%= link_to 'Add a Property', new_property_path, class: "mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect mdl-color--white", method: :get %>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Property Manager</span>
        <nav class="mdl-navigation">
          <%= link_to 'Create a New Property', new_property_path, class: "mdl-navigation__link", method: :get %>
          <%= link_to "View all Properties", properties_path, class: "mdl-navigation__link"%>
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content"><%= yield %></div>
      </main>
    </div>
  </body>
</html>

app/views/properties/_form.html.erb
<div class="mdl-card mdl-shadow--6dp">
  <%= form_with model: @property, local: true do |form| %>
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <h2 class="mdl-card__title-text">
      <%= link_to material_icon.arrow_back, properties_path, class: "mdl-button", method: :get %>  <%= yield :card_title %>
    </h2>
  </div>
  <div class="mdl-card__supporting-text">
    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.text_field :name, class: "mdl-textfield__input", id: :property_name %>
      <%= form.label :name, class: "mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.text_area :description, class: "mdl-textfield__input", id: :property_description %>
      <%= form.label :description, class: "mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.text_field :address, class: "mdl-textfield__input", id: :property_address %>
      <%= form.label :address, class: "mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.text_field :province, class: "mdl-textfield__input", id: :property_province %>
      <%= form.label :province, class: "mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.text_field :city, class: "mdl-textfield__input", id: :property_city %>
      <%= form.label :city, class: "mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.text_field :country, class: "mdl-textfield__input", id: :property_country %>
      <%= form.label :country, class: "mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.number_field :valuation, class: "mdl-textfield__input", id: :property_valuation, step: :any, min: 1 %>
      <%= form.label :valuation, class: "mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield ">
      <%= form.number_field :dimension, class: "mdl-textfield__input", id: :property_dimension, step: :any, min: 1 %>
      <%= form.label :dimension, class: "mdl-textfield__label" %>
    </div>
  </div>

  <div class="mdl-card__actions mdl-card--border">
    <%= form.submit class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
  </div>
  <% end %>
</div>

app/views/properties/edit.html.erb
<% content_for :card_title do %>
Edit Property
<% end %>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <%= render 'form' %>
  </div>
</div>

app/views/properties/index.html.erb
<h2>Listing Properties</h2>

<ul class="demo-list-three mdl-list">
  <% @properties.each do |property| %>
  <li class="mdl-list__item mdl-list__item--three-line">
    <span class="mdl-list__item-primary-content">
      <span><%= property.name %></span>
      <div class="mdl-list__item-text-body">
        <!-- <%= truncate(property.description, lenght: 25) { link_to "view", property_path(property) }  %> -->
        <%= property.address %>
        <p>
          <span class="mdl-chip">
            <span class="mdl-chip__text">RD$<%= property.valuation %></span>
          </span>

          <span class="mdl-chip">
            <span class="mdl-chip__text"><%= property.dimension %> M2</span>
          </span>
        </p>
      </div>
    </span>
    <span class="mdl-list__item-secondary-content">
      <span class="mdl-list__item-secondary-action">
        <%= link_to material_icon.visibility, property_path(property) %>
        <%= link_to material_icon.mode_edit, edit_property_path(property), method: :get %>
      </span>
    </span>
  </li>
  <% end %>
</ul>

app/views/properties/new.html.erb
<% content_for :card_title do %>
New Property
<% end %>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <%= render 'form' %>
  </div>
</div>

app/views/properties/show.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <div class="mdl-card mdl-shadow--6dp" style="width: 100%">
      <div class="mdl-card__title mdl-card--border">
        <h2 class="mdl-card__title-text">
          <%= link_to material_icon.arrow_back, properties_path, class: "mdl-button", method: :get %> <%= @property.name %>
        </h2>
      </div>
      <div class="mdl-card__supporting-text">
        <h6>Features</h6>
        <ul>
          <li><strong>Address:</strong> <i><%= @property.address %></i></li>
          <li><strong>Province:</strong> <i><%= @property.province %></i></li>
          <li><strong>City:</strong> <i><%= @property.city %></i></li>
          <li><strong>Country:</strong> <i><%= @property.country %></i></li>
        </ul>

        <span class="mdl-chip">
          <span class="mdl-chip__text">RD$<%= @property.valuation %></span>
        </span>

        <span class="mdl-chip">
          <span class="mdl-chip__text"><%= @property.dimension %> M2</span>
        </span>
        <hr>
        <h6>Description</h6>
        <%= @property.description %>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <%= link_to "#{ material_icon.mode_edit } Edit".html_safe, edit_property_path(@property), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect", method: :get %>
        <%= link_to "#{ material_icon.delete }
            Delete".html_safe,
            property_path(@property),
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
      </div>
    </div>
  </div>
</div>